[package]
name = "fruity"
version = "0.1.0"
authors = ["Nikolai Vazquez <hello@nikolaivazquez.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Rusty bindings for Apple libraries"
repository = "https://github.com/nvzqz/fruity"
homepage = "https://github.com/nvzqz/fruity"
documentation = "https://docs.rs/fruity"
categories = ["api-bindings", "development-tools::ffi", "os"]
keywords = ["apple", "cocoa", "objc", "foundation", "uikit"]

[features]
default = ["link"]
link = []

[package.metadata.docs.rs]
targets = ["x86_64-apple-darwin"]
